services:
  postgres_sources:
    image: postgres:15-alpine
    container_name: postgres_sources
    environment:
      POSTGRES_USER: ${SRC_DB_USER}
      POSTGRES_PASSWORD: ${SRC_DB_PASS}
      POSTGRES_DB: ${SRC_DB_NAME}
    ports:
      - "${SRC_DB_HOST_PORT}:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - data_platform_net

volumes:
  postgres_data:

networks:
  data_platform_net:
    external: true