USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS LOADER_ROLE COMMENT = 'Airbyte service role, RAW db only';
CREATE ROLE IF NOT EXISTS TRANSFORM_ROLE COMMENT = 'Airflow/dbt service role, RAW read + ANALYTICS write';

CREATE USER IF NOT EXISTS AIRBYTE_SVC
  RSA_PUBLIC_KEY = '<PASTE_AIRBYTE_PUBLIC_KEY_HERE>'
  DEFAULT_ROLE = LOADER_ROLE
  DEFAULT_WAREHOUSE = LOADING_WH
  MUST_CHANGE_PASSWORD = FALSE
  COMMENT = 'Service account used exclusively by Airbyte';

CREATE USER IF NOT EXISTS AIRFLOW_SVC
  RSA_PUBLIC_KEY = '<PASTE_AIRFLOW_PUBLIC_KEY_HERE>'
  DEFAULT_ROLE = TRANSFORM_ROLE
  DEFAULT_WAREHOUSE = TRANSFORM_WH
  MUST_CHANGE_PASSWORD = FALSE
  COMMENT = 'Service account used exclusively by Airflow/dbt';

GRANT ROLE LOADER_ROLE TO USER AIRBYTE_SVC;
GRANT ROLE TRANSFORM_ROLE TO USER AIRFLOW_SVC;

USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS LOADING_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Airbyte extract/load — I/O bound, keep it small and auto-suspended';

CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'dbt transformations, triggered by Airflow';

CREATE DATABASE IF NOT EXISTS RAW COMMENT = 'Airbyte landing zone: PAGILA_RAW / SAKILA_RAW schemas';
CREATE DATABASE IF NOT EXISTS ANALYTICS COMMENT = 'dbt staging/intermediate/marts/analytics schemas';

-- ---------------------------------------------------------------------
-- LOADER_ROLE: full control inside RAW only, nothing in ANALYTICS
-- ---------------------------------------------------------------------
GRANT USAGE ON WAREHOUSE LOADING_WH TO ROLE LOADER_ROLE;
GRANT USAGE, CREATE SCHEMA ON DATABASE RAW TO ROLE LOADER_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE RAW TO ROLE LOADER_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE RAW TO ROLE LOADER_ROLE;

-- ---------------------------------------------------------------------
-- TRANSFORM_ROLE: read-only on RAW, full control inside ANALYTICS only
-- ---------------------------------------------------------------------
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE TRANSFORM_ROLE;
GRANT USAGE ON DATABASE RAW TO ROLE TRANSFORM_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE RAW TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE RAW TO ROLE TRANSFORM_ROLE;
-- schemas already created by Airbyte before this script's first run need an explicit grant too:
GRANT USAGE ON ALL SCHEMAS IN DATABASE RAW TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE RAW TO ROLE TRANSFORM_ROLE;

GRANT USAGE, CREATE SCHEMA ON DATABASE ANALYTICS TO ROLE TRANSFORM_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE ANALYTICS TO ROLE TRANSFORM_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE ANALYTICS TO ROLE TRANSFORM_ROLE;
GRANT ALL ON FUTURE VIEWS IN DATABASE ANALYTICS TO ROLE TRANSFORM_ROLE;
