x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASS}@airflow_metadata:5432/${AIRFLOW_DB_NAME}
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
    AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    AIRFLOW__CORE__LOGGING_LEVEL: 'INFO'
    SF_ACCOUNT: ${SF_ACCOUNT}
    SF_USER: ${SF_USER}
    SF_PASSWORD: ${SF_PASSWORD}
    SF_DATABASE: ${SF_DATABASE}
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ../pagila_analytics:/opt/pagila_analytics
  user: "${AIRFLOW_UID:-50000}:0"
  networks:
    - data_platform_net

services:
  airflow_metadata:
    image: postgres:15-alpine
    container_name: airflow_metadata
    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASS}
      POSTGRES_DB: ${AIRFLOW_DB_NAME}
    volumes:
      - airflow_metadata_data:/var/lib/postgresql/data
    networks:
      - data_platform_net

  airflow_webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: bash -c "airflow db migrate && airflow users create --username admin --password admin_password --firstname Admin --lastname Admin --role Admin --email admin@example.com && airflow webserver"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      - airflow_metadata

  airflow_scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: bash -c "airflow scheduler"
    restart: always
    depends_on:
      airflow_webserver:
        condition: service_healthy

volumes:
  airflow_metadata_data:

networks:
  data_platform_net:
    external: true